name: Reusable Deploy
on:
  workflow_call:
    outputs:
      result:
        description: The result of deploy
        value: ${{ jobs.deploy.outputs.outcome }}
    inputs:
      artifact-name:
        description: The name iof deployable artifact
        required: false
        default: dist
        type: string

    secrets:
      some-secret:
        required: false
jobs:
  deploy:
    outputs:
      outcome: ${{steps.result.outputs.step-result}}
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/download-artifact@v6
        with:
          path: ${{inputs.artifact-name}}
      - name: List files
        run: ls
      - name: Output information
        run: echo "Deploying & uploading..."
      - name: Set result output
        id: result
        run: echo "step-result=success" >> $GITHUB_OUTPUT